create table "public"."pubsub_logs" (
    "id" bigint generated by default as identity not null,
    "pubsub_data" jsonb,
    "attributes" jsonb,
    "message_id" text,
    "publish_time" timestamp with time zone,
    "ordering_key" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."pubsub_logs" enable row level security;

CREATE UNIQUE INDEX pubsub_logs_pkey ON public.pubsub_logs USING btree (id);

alter table "public"."pubsub_logs" add constraint "pubsub_logs_pkey" PRIMARY KEY using index "pubsub_logs_pkey";

grant delete on table "public"."pubsub_logs" to "anon";

grant insert on table "public"."pubsub_logs" to "anon";

grant references on table "public"."pubsub_logs" to "anon";

grant select on table "public"."pubsub_logs" to "anon";

grant trigger on table "public"."pubsub_logs" to "anon";

grant truncate on table "public"."pubsub_logs" to "anon";

grant update on table "public"."pubsub_logs" to "anon";

grant delete on table "public"."pubsub_logs" to "authenticated";

grant insert on table "public"."pubsub_logs" to "authenticated";

grant references on table "public"."pubsub_logs" to "authenticated";

grant select on table "public"."pubsub_logs" to "authenticated";

grant trigger on table "public"."pubsub_logs" to "authenticated";

grant truncate on table "public"."pubsub_logs" to "authenticated";

grant update on table "public"."pubsub_logs" to "authenticated";

grant delete on table "public"."pubsub_logs" to "service_role";

grant insert on table "public"."pubsub_logs" to "service_role";

grant references on table "public"."pubsub_logs" to "service_role";

grant select on table "public"."pubsub_logs" to "service_role";

grant trigger on table "public"."pubsub_logs" to "service_role";

grant truncate on table "public"."pubsub_logs" to "service_role";

grant update on table "public"."pubsub_logs" to "service_role";



