import type { Metadata } from "next";

import { ModeToggle } from "@/components/mode-toggle";
import Header from "../(marketing)/components/header";
import Footer from "../(marketing)/components/footer";
import { RouteParams } from "@/app/types/enterprise";
import { I18nProviderClient } from "@/locales/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<RouteParams>;
}>) {
  const { locale } = await params;

  return (
    <I18nProviderClient locale={locale}>
      <Header className="sticky top-0 z-10 bg-background" />
      <main className="flex-1">{children}</main>
      <div className="fixed bottom-4 right-5 z-50">
        <ModeToggle />
      </div>
      <Footer />
    </I18nProviderClient>
  );
}
