import type { Metadata } from "next";

import { ModeToggle } from "@/components/mode-toggle";
import Footer from "../../(marketing)/components/footer";
import Header from "../../(marketing)/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthErrorPage() {
  return (
    <>
      <Header className="sticky top-0 z-10 bg-background" />
      <main className="flex-1">
        <p>Sorry, something went wrong. Auth Error</p>
      </main>
      <div className="fixed bottom-4 right-5 z-50">
        <ModeToggle />
      </div>
      <Footer />
    </>
  );
}
