import type { Metadata } from "next";
import { AppsInfoSheetProvider } from "../providers/apps-info-sheet";

import { AppsSidebar } from "./components/apps-sidebar";
import MableTopBar from "../../../../lib/emm/components/mable-top-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppsInfoSheetProvider>
      <div className="flex">
        <AppsSidebar className="hidden xl:block" />
        <div className="flex-1 min-w-0">
          <MableTopBar className="lg:hidden" />
          {children}
        </div>
      </div>
    </AppsInfoSheetProvider>
  );
}
