import type { Metadata } from "next";
import MableTopBar from "../../../../lib/emm/components/mable-top-bar";
import { DeviceSidebar } from "./components/device-sidebar";
import { RouteParams } from "@/lib/types/enterprise";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<RouteParams>;
}) {
  const { enterpriseId } = await params;
  return (
    <div className="flex h-full">
      <DeviceSidebar className="hidden xl:block" enterpriseId={enterpriseId} />
      <div className="flex-1 min-w-0">
        <MableTopBar className="lg:hidden" />
        {children}
      </div>
    </div>
  );
}
