import { ModeToggle } from "@/components/mode-toggle";
import type { Metadata } from "next";
import Header from "./components/header";
import { SignInFormProvider } from "./providers/sign-in";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container mx-auto px-4 md:px-6 xl:px-[70px] flex flex-col">
      <Header className="z-50" />
      <main className="flex-1 z-40">
        <SignInFormProvider>{children}</SignInFormProvider>
      </main>

      <div className="fixed bottom-4 right-5 z-50">
        <ModeToggle />
      </div>
    </div>
  );
}
